name: Deploy on Test Server
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  SFTP-Mirror:
    name: SFTP Mirror
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: SFTP Mirror
      uses: pyxn/sftp-mirror@v1.0.0
      env:
        HOSTNAME: ${{ secrets.HOSTNAME_TEST }}
        USERNAME: ${{ secrets.USERNAME_TEST }}
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        PATH_LOCAL: "./public_html/"
        PATH_REMOTE: "./newcitybetterlife.com/public_html/"
        PROTOCOL: sftp
        PORT: 22
        ARGS: --verbose --delete